#!/bin/env python

import os
import shutil
import io
import datetime
import sys

def dump_to_file( f, s ):
	if sys.version_info < (3, 0):
		f.write( s )
	else:
		f.write( bytes(s, 'UTF-8') )

os.chdir( os.getcwd() )

print( 'cleaning up release folder...' )
try:
	shutil.rmtree( 'release' )
except OSError:
	pass

os.makedirs( 'release' )

print( 'cleaning up JavaScript bin folder...' )
try:
	shutil.rmtree( 'dev/js/bin' )
except OSError:
	pass

os.makedirs( 'dev/js/bin' )


jsf = open( 'dev/js/bin/lfadmin.js', 'wb' )

jsfile  =  '/*****************************************************************************/\n'
jsfile += '/* IMPORTANT: DO NOT EDIT THIS FILE!                                         */\n'
jsfile += '/* EDIT THE FILES IN THE SRC FOLDER INSTEAD AND USE THE BUILD SCRIPT TO      */\n'
jsfile += '/* GENERATE THIS FILE                                                        */\n'
jsfile += '/*****************************************************************************/\n\n'
dump_to_file( jsf, jsfile )

for filename in [ 'dev/js/header', 'dev/js/src/general.js',
		'dev/js/src/feededitor.js', 'dev/js/src/mediaobjecteditor.js',
		'dev/js/src/playlisteditor.js', 'dev/js/src/recordeditor.js',
		'dev/js/src/serieseditor.js' ]:
	infile = open( filename )
	for line in infile:
		dump_to_file( jsf, line )
	infile.close()
jsf.close()

print( 'copy template files...' )
shutil.copytree( 'dev/templates', 'release/templates' )

print( 'copy gfx files...' )
shutil.copytree( 'dev/gfx', 'release/gfx' )

print( 'copy php files...' )
shutil.copytree( 'dev/php', 'release/php' )

print( 'copy js files...' )
os.makedirs( 'release/js' )

shutil.copytree( 'dev/js/imports', 'release/js/imports' )
shutil.copytree( 'dev/js/bin',     'release/js/bin' )

print( 'copy general files...' )
shutil.copy( 'dev/index.php', 'release' )

print( 'writing build time...' )
f = open( 'release/buildtime.txt', 'wb' )
dump_to_file( f, str(datetime.datetime.now()) )

print( "Please remember to \033[1mupdate the php/config.php!\033[0m" )
