(:(format):(Audio Podcast):(<a href="http://lernfunk.de/media/(:id:)" class="dll format_link">Audio</a>):():)
(:(format):(Video Podcast):(<a href="http://lernfunk.de/media/(:id:)" class="dll format_link">Dozent&nbsp;<span style="font-size:9px;">Video</span></a>):():) 
(:(format):(Flash HD):(<a href="http://lernfunk.de/media/(:id:)" class="dll format_link">HD-Video</a>):():) 
(:(format):(Screenrecording Podcast):(<a href="http://lernfunk.de/media/(:id:)" class="dll format_link">Bildschirm&nbsp;<span style="font-size:9px;">Video</span></a>):():)
(:(format):(Opencast Matterhorn):(<a href="http://lernfunk.de/media/(:id:)" class="epl format_link enhanced_player"><img src="./template/uni_os_red/img/icons/erweitert.png" />Erweiterter Player</a>):():)
(:(format):(Opencast Matterhorn 1.1):(<a href="http://lernfunk.de/media/(:id:)" class="epl format_link enhanced_player"><img src="./template/uni_os_red/img/icons/erweitert.png" />Erweiterter Player</a>):():)
(:(format):(virtPresenter II (Flash)):(<a href="http://lernfunk.de/media/(:id:)" class="epl format_link enhanced_player"><img src="./template/uni_os_red/img/icons/erweitert.png" />Erweiterter Player</a>):():)
