(:(format):(Audio Podcast):(<a href="(:url:)" class="format_link">Audio</a>):():)
(:(format):(Video Podcast):(<a href="(:url:)" class="format_link">Dozent&nbsp;<span style="font-size:9px;">Video</span></a>):():) 
(:(format):(Screenrecording Podcast):(<a href="(:url:)" class="format_link">Bildschirm&nbsp;<span style="font-size:8px;">Video</span></a>):():)
(:(format):(Opencast Matterhorn):(<a href="(:url:)" class="format_link enhanced_player"><img src="./template/uni_os_red/img/icons/erweitert.png">Erweiterter Player</a>):():)
(:(format):(virtPresenter II (Flash)):(<a href="(:url:)" class="format_link enhanced_player"><img src="./template/uni_os_red/img/icons/erweitert.png">Erweiterter Player</a>):():)
