#/bin/bash!

echo 'building master javascript document...'

cd src
echo '/*****************************************************************************/'  > ../bin/lfadmin.js
echo '/* IMPORTANT: DO NOT EDIT THIS FILE!                                         */' >> ../bin/lfadmin.js
echo '/* EDIT THE FILES IN THE SRC FOLDER INSTEAD AND USE THE BUILD SCRIPT TO      */' >> ../bin/lfadmin.js
echo '/* GENERATE THIS FILE                                                        */' >> ../bin/lfadmin.js
echo '/*****************************************************************************/' >> ../bin/lfadmin.js
echo '' >> ../bin/lfadmin.js
cat ../header general.js feededitor.js mediaobjecteditor.js playlisteditor.js recordeditor.js serieseditor.js >> ../bin/lfadmin.js
cd ..
